source = $HOME/.cache/hellwal/hyprland-colors.conf
background {
    monitor =
    path = $HOME/.bg
    blur_passes = 2
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

general {
    immediate_render = false
    ignore_empty_input = true
    fail_timeout = 2000
    hide_cursor = true
    screencopy_mode = 0
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.2)
    font_color  = rgb(205, 214, 244)
    fade_on_empty = false
    font_family = "JetBrainsMono Nerd Font Bold"
    placeholder_text = <span foreground="##cdd6f4">Hi, $USER</span>
    hide_input = false
    position = 0, -180
    halign = center
    valign = center
    check_color = rgb(108, 112, 134)
    fail_color = rgb(243, 139, 168)
    fail_text =  <b>Wrong: $ATTEMPTS</b>
}

# Hour-Time
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%H")"
    color = $color7
    font_size = 180
    font_family = "JetBrainsMono Nerd Font Bold"
    position = 0, 300
    halign = center
    valign = center
}

# Minute-Time
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%M")"
    color = $color7
    font_size = 180
    font_family = "JetBrainsMono Nerd Font Bold"
    position = 0, 75
    halign = center
    valign = center
}

# Day-Date-Month
label {
    monitor =
    text = cmd[update:1000] echo "<span color='##ffffff99'>$(date '+%A, ')</span><span>$(date '+%d %B')</span>"
    color = $color4
    font_size = 30
    font_family = "JetBrainsMono Nerd Font Bold"
    position = 0, -80
    halign = center
    valign = center
}

